version: '3'
services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      ENV: dev
      JDBC_URL: jdbc:postgresql://db:5432/api_marketplace
      JDBC_USER: postgres
      JDBC_PASSWORD: example


  db:
    build: docker/images/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:7.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"