package com.example.demo.constant;

public enum ErrorCode {
    PROTOCOL_UNAUTHORIZED,
    TOKEN_INVALID,
    TOKEN_UNAUTHORIZED,
    TOKEN_EXPIRED,
    PUBLISHER_UNAUTHORIZED,
    FORBIDDEN,
    BAD_REQUEST,
    METHOD_NOT_ALLOWED,
    UNSUPPORTED_MEDIA_TYPE,
    API_NOT_FOUND,
    PUBLISHER_NOT_FOUND,
    SERVER_ERROR
}
